### ISSUE TITLE
Shopping Cart: Default Quantity

### ISSUE THREAD

**Issue by jasonpoulos** [caitlynmayers/dukes#72] opened 2016-12-01 20:34 UTC
Default item quantities aren't showing up in the shopping cart
<img width="477" alt="screen shot 2016-12-01 at 3 29 28 pm" src="https://cloud.githubusercontent.com/assets/24302252/20811417/9a338b8a-b7db-11e6-91f5-ddedcaaa54a9.png">

**Comment by caitlynmayers** [comment] 2016-12-06 21:21
Duplicate of #28.

**Closed as completed by caitlynmayers** 2016-12-06 21:21 UTC
Labels: Chrome, Desktop, Function
